-- seasons
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('1', '2012', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('2', '2013', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('3', '2014', 1);

-- players
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '1', 'Roger', 0, '1981-08-14', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '2', 'Yves', 0, '1983-08-11', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '3', 'Beni', 0, '1981-08-13', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '4', 'Mösi', 1, '1981-08-6', '2009-01-01', CURRENT_TIMESTAMP);

-- events
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST) VALUES (
  '1', '2014-01-01', '1. Event', '3', CURRENT_TIMESTAMP, '1');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST) VALUES (
  '2', '2014-02-01', '2. Event', '3', CURRENT_TIMESTAMP, '2');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST) VALUES (
  '3', '2014-03-01', '3. Event', '3', CURRENT_TIMESTAMP, '3');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST) VALUES (
  '4', '2014-04-01', '4. Event', '3', CURRENT_TIMESTAMP, '4');