-- seasons
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('1', '2012', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('2', '2013', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('3', '2014', 1);

-- events
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED) VALUES
  ('1', '2014-01-01', '1. Event', '3', CURRENT_TIMESTAMP);
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED) VALUES
  ('2', '2014-02-01', '2. Event', '3', CURRENT_TIMESTAMP);
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED) VALUES
  ('3', '2014-03-01', '3. Event', '3', CURRENT_TIMESTAMP);
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED) VALUES
  ('4', '2014-04-01', '4. Event', '3', CURRENT_TIMESTAMP);