-- seasons
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('1', '2012', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('2', '2013', 0);
INSERT INTO T_SEASON (_UUID, _NAME, _CURRENT) VALUES ('3', '2014', 1);

-- venues
INSERT INTO T_VENUE (_UUID, _NAME, _STREET, _ZIP, _CITY, _COUNTRY, _CURRENT, _LATITUDE, _LONGITUDE, _UPDATED) VALUES (
  '1', '@Roger', 'Kaffeestrasse 18', '8180', 'Bülach', 'CH', 1, 47.512264, 8.537114, CURRENT_TIMESTAMP);
INSERT INTO T_VENUE (_UUID, _NAME, _STREET, _ZIP, _CITY, _COUNTRY, _CURRENT, _LATITUDE, _LONGITUDE, _UPDATED) VALUES (
  '2', '@Nils', 'Kantonsschulstrasse', '8180', 'Bülach', 'CH', 0, 47.518704, 8.546742, CURRENT_TIMESTAMP);

-- players
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '1', 'Roger', 0, '1981-08-14', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '2', 'Yves', 0, '1983-08-11', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '3', 'Beni', 0, '1981-08-13', '2008-01-01', CURRENT_TIMESTAMP);
INSERT INTO T_PLAYER (_UUID, _NICKNAME, _GUEST, _BIRTHDAY, _JOINED, _UPDATED) VALUES (
  '4', 'Buri', 1, '1981-08-6', '2009-01-01', CURRENT_TIMESTAMP);

-- events
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST, _VENUE) VALUES (
  '1', '2014-01-01', '1. Event', '3', CURRENT_TIMESTAMP, '1', '1');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST, _VENUE) VALUES (
  '2', '2014-02-01', '2. Event', '3', CURRENT_TIMESTAMP, '2', '2');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST, _VENUE) VALUES (
  '3', '2014-03-01', '3. Event', '3', CURRENT_TIMESTAMP, '3', '1');
INSERT INTO T_EVENT (_UUID, _DATE, _NAME, _SEASON, _UPDATED, _HOST, _VENUE) VALUES (
  '4', '2014-04-01', '4. Event', '3', CURRENT_TIMESTAMP, '4', '2');

-- tournaments
INSERT INTO T_TOURNAMENT (_UUID, _EVENT, _RESULT_SUBMITTED_BY, _ROUND, _STATUS, _UPDATED) VALUES (
  '1', '1', '1', 1, 3, CURRENT_TIMESTAMP);
INSERT INTO T_TOURNAMENT (_UUID, _EVENT, _RESULT_SUBMITTED_BY, _ROUND, _STATUS, _UPDATED) VALUES (
  '2', '1', '1', 2, 2, CURRENT_TIMESTAMP);
INSERT INTO T_TOURNAMENT (_UUID, _EVENT, _RESULT_SUBMITTED_BY, _ROUND, _STATUS, _UPDATED) VALUES (
  '3', '1', '1', 3, 1, CURRENT_TIMESTAMP);

-- tournament results
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '1', '1', 4, 0, 4, '1', CURRENT_TIMESTAMP, 20, 0);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '2', '2', 4, 5, 3, '1', CURRENT_TIMESTAMP, 20, 0);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '3', '3', 4, 10, 2, '1', CURRENT_TIMESTAMP, 20, 20);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '4', 4, 0, 1, '1', CURRENT_TIMESTAMP, 20, 100);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '5', '2', 4, 10, 4, '1', CURRENT_TIMESTAMP, 20, 40);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '6', '1', 4, 15, 2, '1', CURRENT_TIMESTAMP, 20, 40);

INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '7', '2', 3, 5, 3, '1', CURRENT_TIMESTAMP, 20, 0);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _ELIMINATED_BY, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '8', '1', 2, 10, 2, '1', CURRENT_TIMESTAMP, 20, 40);
INSERT INTO T_TOURNAMENT_RESULT (_UUID, _PLAYER, _POINTS, _RANK, _TOURNAMENT, _UPDATED, _ANTE, _WIN) VALUES (
  '9', 1, 15, 1, '1', CURRENT_TIMESTAMP, 20, 80);